# Debtmap Configuration

[scoring]
# Weights for different scoring factors (must sum to 1.0)
# Balanced approach: coverage important but ROI and criticality guide smart prioritization
coverage = 0.35    # Weight for test coverage gaps
complexity = 0.15  # Weight for code complexity
roi = 0.25         # Weight for return on investment (now calculated properly!)
semantic = 0.05    # Weight for semantic/role factors
dependency = 0.20  # Weight for critical path (functions with many callers)

[thresholds]
complexity = 10
duplication = 50
max_file_length = 500
max_function_length = 50

[languages]
enabled = ["rust"]

[ignore]
patterns = [
    "target/**",
    "venv/**",
    "node_modules/**",
    "*.min.js",
    "benches/**"
]

[output]
default_format = "terminal"

[external_api]
# Enable automatic external API detection for testing
detect_external_api = false

# However, we can still explicitly mark certain functions as APIs if needed
# (Currently empty since debtmap doesn't expose any external APIs)
api_functions = []
api_files = []
