[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = [
    { name = "hashbrown" },
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]
skip-tree = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "none"
yanked = "warn"
ignore = [
    "RUSTSEC-2024-0436",  # paste crate - unmaintained, will need to find alternative
]

[licenses]
allow = [
    "MIT", 
    "Apache-2.0", 
    "CC0-1.0", 
    "Unicode-3.0", 
    "MPL-2.0", 
    "BSL-1.0", 
    "Unlicense", 
    "ISC",
]
exceptions = [
    { allow = ["Apache-2.0 WITH LLVM-exception"], name = "linux-raw-sys" },
    { allow = ["Apache-2.0 WITH LLVM-exception"], name = "rustix" },
    { allow = ["Apache-2.0 WITH LLVM-exception"], name = "wasi" },
    { allow = ["LGPL-3.0"], name = "malachite", version = "*" },
    { allow = ["LGPL-3.0"], name = "malachite-base", version = "*" },
    { allow = ["LGPL-3.0"], name = "malachite-bigint", version = "*" },
    { allow = ["LGPL-3.0"], name = "malachite-nz", version = "*" },
    { allow = ["LGPL-3.0"], name = "malachite-q", version = "*" },
    { allow = ["Unicode-DFS-2016"], name = "unicode_names2" },
]
confidence-threshold = 0.8

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []