[toolchain]
channel = "1.89.0"
components = ["rustfmt", "clippy", "llvm-tools-preview"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc"
]
