name: Bug Report
description: Report a bug in debtmap
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us identify and fix the issue.

  - type: input
    id: version
    attributes:
      label: Debtmap Version
      description: Output of `debtmap --version`
      placeholder: "debtmap 0.2.8"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.75.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected debtmap to analyze my Rust project without errors..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, debtmap crashed with a panic..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Run `debtmap analyze .`
        2. See error in terminal
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Paste any error messages or logs (use backticks for formatting)
      render: shell
      placeholder: |
        $ debtmap analyze .
        thread 'main' panicked at 'index out of bounds'...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem (code examples, configuration files, etc.)
      placeholder: "I'm analyzing a project with 50,000+ lines of Rust code..."
